### ISSUE TITLE
find API

### ISSUE THREAD

**Issue by nataliarusu** [fac26/Dominic_Natalia_http#2]
find free APIs for the project

**Comment by nataliarusu** [comment]
1. we can display the bitcoin currency on our project. To achieve this we should create a "get bitcoin value now" button that will return the bitcoin currency to the current time. The API link: https://api.coindesk.com/v1/bpi/currentprice.json
2. we can display the currency exchange, a user enters the 'amount and currency from' and 'currency to', and as a result, the user gets the currency exchange displayed on our project. The API is https://rapidapi.com/natkapral/api/currency-converter5/details. The problem is request **has been blocked by CORS policy: No 'Access-Control-Allow-Origin'_**. It might be the API key is required.

**Comment by nataliarusu** [comment]
3. since you suggested that you would like the project to be about countries we can use this API https://restcountries.com/v3.1/name/. I've tested it already. what we get back is information about the country 
 ['GB', 'UK', 'Great Britain'], area: 242900, borders: ['IRL'], capital: ['London']car: {signs: Array(1), side: 'left'}, continents: ['Europe']
currencies: {GBP: {…}}, languages: {eng: 'English'}
name: {common: 'United Kingdom', official: 'United Kingdom of Great Britain and Northern Ireland', population: 67215293 {…}}
population: 67215293

- we can display some of the countries and have a link to google maps. 
- we can have an input search to display info on user choice. we should test it though

**Comment by nataliarusu** [comment]
@DominicSimpson

Our project should reflect a mashup of different data
4. we can try to use https://documenter.getpostman.com/view/1134062/T1LJjU52#4829d16f-0f4e-43ec-886e-68ebad1221d8 and get the data about cities of the country a user has chosen. 

Are you happy to use APIs 3 and 4?

**Comment by DominicSimpson** [comment]
We could use APIs 3 and 4 - that means we have two APIs covered. Not sure what we'd do about images, but maybe that's not so important for now?

**Comment by DominicSimpson** [comment]
I'm happy to start with 3 and 4.

**Comment by nataliarusu** [comment]
Great, thank you, Dominic.
