### ISSUE TITLE
The weather functionality at the bottom of the page doesn't work

### ISSUE THREAD

**Issue by DFLLinton** [fac26/Dominic_Natalia_http#25]
In my experience it renders 'It is a day in Rome.

The temperature is , wind speed is .'

Having looked at the javascript I can't see an issue so may be some sort of problem with the fetch functionality

**Comment by konstantinakatmada** [comment]
It also isn't working for me, but I get a different message with all of the countries I try, "No Data available"

**Comment by nataliarusu** [comment]
Thanks, both of you. Unfortunately, the weather API doesn't work perfectly. Sometimes it crashes. We can't do much about it. What we did is we handled and displayed different error messages depending on the response we get from the server. If the server has crashed we display that we couldn't fetch the data message. If the data was not found and we receive a response 404 we display the message "No Data available". Unfortunately, it is the downside of using free APIs.

**Comment by DFLLinton** [comment]
Okay interesting, that's good to know and I'm sorry to hear that the your API crashes so much
