### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by konstantinakatmada** [fac26/Dominic_Natalia_http#26]
Excellent website! Only one issue I have found so far. The openstreetmap.org link is not working. When I am inspecting it, the link works perfectly fine, but on the actual website it leads to about: blank.
The google maps link works perfectly fine though, and I think this is the one most people will be clicking.

**Comment by konstantinakatmada** [comment]
It should be added that it doesn't work on your initial github pages deployment of United Kingdom, it seems to be working with some other countries.

**Comment by DominicSimpson** [comment]
Hi Konstantin, thanks for letting us know that you tried OpenStreetMap and it didn't work. We've just tried it and it does seem to work - though sometimes there are a couple of seconds while it displays about:blank before it brings up the data. 
Try a country and then see if it works this time?

**Comment by konstantinakatmada** [comment]
Hey Dominic,
You are right! :) if I stay at the page without going to another tab at my browser it opens after 5 seconds. All other countries, except for the UK that you used for your github pages paradigm, load immediately. So, I am closing this issue
Cheers, 
Konstantina
